apiVersion: rbac.authorization.k8s.io/v1  
kind: Role  
metadata:  
  name: services-getter  
  namespace: kube-system  
rules:  
- apiGroups: [""]  
  resources: ["services", "endpoints"]  
  verbs: ["get", "list", "watch", "create"]