apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    app: wordpress
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      imagePullSecrets:
      - name: acr-credential
      containers:
      - image: registry.cn-beijing.aliyuncs.com/argocd-local/wordpress-img:php74-v6.4.3_009
        name: wordpress
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: wordpress-secret
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
        - name: wordpress-plugin-storage
          mountPath: /usr/share/nginx/html/wp-content/upgrade/
      volumes:
      - name: config
        configMap:
          name: nginxconfs
      - name: wordpress-plugin-storage
        persistentVolumeClaim:
          claimName: wp-content-pv-wpsix