apiVersion: v1
kind: PersistentVolume
metadata:
  name: wpsix-content-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/pvdata/wordpress/wp-content/upgrade/
    server: 192.168.23.82
  
