apiVersion: v1
kind: Pod
metadata:
  name: alicloud-oss-pod
spec:
  containers:
    - name: alicloud-oss-container
      image: nginx:1.7.9
      volumeMounts:
        - mountPath: "/var/www/html"
          name: oss-volume
  volumes:
    - name: oss-volume
      persistentVolumeClaim:
        claimName: posts-images-pvc-wpsix